export const COLORS = {
  primary: '#fda427',
  primaryBlank: '#f37904',
  primaryDark: '#f37904',
  secondary: '#8ec7ff',
  secondaryBlank: '#e2f2ff',
  secondaryDark: '#046cfd',
  alertColor: '#ff2d11',
  alertColorBlank: '#ffc8b9',
  alertColorDark: '#ef0300',
  analogous: '#fafafa',
  analogousBlank: '#ffffff',
  triadic: '#c1eff4',
  triadicBlank: '#e6f8fb',
  triadicBlank2: '#e0f7fa',
  triadicDark: '#008394',
  text: 'black',
};
